openapi: 3.0.3
info:
  title: Distributed Message Room API
  version: 0.1.0
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: A well-orchestrated high-performance proxy pass.
servers:
  - url: 'http://localhost:3000'
paths:
  /messages:
    post:
      summary: ''
      operationId: post-messages
      responses:
        '202':
          description: Accepted
      parameters:
        - name: X-Send-To
          in: header
          required: true
          schema:
            type: string
            example: Classifier
          description: Participant name to send the message to.
        - name: X-Sent-By
          in: header
          required: true
          schema:
            type: string
            example: NLib
          description: Name of the participant that sent the message.
        - name: X-Model-Type
          in: header
          required: true
          schema:
            type: string
            example: application/vnd.classifier.classification+json;version=1
          description: Payload type when decrypted.
        - name: X-Message-Id
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: bb20ba03-5e52-4a61-bcc1-0ad538f1b448
          description: 'Uuid generated by the sender of a message for correlating async responses to a specific request. '
        - name: X-Message-Id-Ref
          in: header
          schema:
            type: string
            format: uuid
            example: 545226ad-0b8d-4ccb-b83f-6b3ad8d44ec8
          description: Reference to the original X-Message-Id we are replying to.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              description: Encrypted payload that is decryptable only by the participant set in X-Send-To header.
              example: uCsJ1JobnE2Ll/kwu7crbfogagHrwtzDwbLf5mtYU8g=
        description: ''
      callbacks:
        error:
          '{sent-by}/messages':
            post:
              description: '* Payload is always encrypted, decrypted payloads included for clarity'
              parameters:
                - name: X-Sent-By
                  in: header
                  required: true
                  schema:
                    type: string
                    example: NLib
                  description: Name of the participant that sent the message.
                - name: X-Send-To
                  in: header
                  required: true
                  schema:
                    type: string
                    example: Classifier
                  description: Participant name to send the message to.
                - name: X-Model-Type
                  in: header
                  required: true
                  schema:
                    type: string
                    example: application/vnd.dmr.error+json;version=1
                  description: Payload type when decrypted.
                - name: X-Message-Id
                  in: header
                  required: true
                  schema:
                    type: string
                    format: uuid
                    example: bb20ba03-5e52-4a61-bcc1-0ad538f1b448
                  description: 'Uuid generated by the sender of a message for correlating async responses to a specific request. '
                - name: X-Message-Id-Ref
                  in: header
                  schema:
                    type: string
                    format: uuid
                    example: 545226ad-0b8d-4ccb-b83f-6b3ad8d44ec8
                  description: Reference to the original X-Message-Id we are replying to.
              requestBody:
                required: true
                content:
                  text/plain:
                    schema:
                      type: string
                      example: ewogICJtZXNzYWdlIjogIlVuYWJsZSB0byBjb250YWN0IHBhcnRpY2lwYW50ISIsCiAic3RhdHVzIjogNTA0IAp9
                      description: Encrypted payload.
              responses:
                '202':
                  description:
      description: ''
